### ISSUE TITLE
Pitch and Yaw are inverted (3dof gyro)

### ISSUE THREAD

**Issue by yuripourre** [yigiter/Demo6DoF#5]
Hello, I am testing the app in a Zefone 3 and rotating the phone seems to produce the wrong output. Rotating the Pitch axis changes the Yaw axis and rotating the Yaw axis changes the Pitch axis. I am trying the 3DoF Gyro mode.

Anyone else is having the same output? Hope it is not caused by the update I made.

**Comment by dixon1e** [comment]
Will try on a Google Pixel 3 and an LG Stylus.

**Comment by dixon1e** [comment]
@yuripourre I am seeing the same behavior. When you changed to Landscape mode, was there a possibility the axis variables were swapped?

**Comment by yuripourre** [comment]
@dixon1e thank you for confirming it. Locking the app as landscape shouldn't be an issue, I tested it as portrait and had the same result.
I will have some time next week, and will try to investigate if I changed something unintentionally while upgrading.

**Comment by yuripourre** [comment]
@dixon1e you are right. Checking the code it defines an initial orientation and if app starts as landscape the axis are swapped.

Locking it as portrait solves the problem.
